projects:
  app:
    schemaPath: app/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: app/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
