projects:
  app:
    schemaPath: app/graphql/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:${env:PORT}
  prisma:
    schemaPath: app/graphql/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
