steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-back-proxy:$BRANCH_NAME-$SHORT_SHA', './packages/frank-back-auth-proxy']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-back-proxy:$BRANCH_NAME-$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-back-proxy=gcr.io/$PROJECT_ID/frank-back-proxy:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']


- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-back-uploader:$BRANCH_NAME-$SHORT_SHA', './packages/frank-back-api-images']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-back-uploader:$BRANCH_NAME-$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-back-uploader=gcr.io/$PROJECT_ID/frank-back-uploader:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']
