steps:
- name: ubuntu
  args: ['bash', './registry_npmjs.sh', '$_NPM_TOKEN']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-back-graph:$BRANCH_NAME-$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-back-graph:$BRANCH_NAME-$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-back-graph=gcr.io/$PROJECT_ID/frank-back-graph:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']


- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-back-proxy:$BRANCH_NAME-$SHORT_SHA', './auth-proxy']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-back-proxy:$BRANCH_NAME-$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-back-proxy=gcr.io/$PROJECT_ID/frank-back-proxy:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']


- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/frank-back-uploader:$BRANCH_NAME-$SHORT_SHA', './image-uploader']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/frank-back-uploader:$BRANCH_NAME-$SHORT_SHA']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/$_DEPLOYMENT', 'frank-back-uploader=gcr.io/$PROJECT_ID/frank-back-uploader:$BRANCH_NAME-$SHORT_SHA']
  env: ['CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER', 'CLOUDSDK_COMPUTE_ZONE=$_ZONE']
