version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.13
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: '${HOST}'
            port: '${PORT}'
            database: '${BASE}'
            user: '${USER}'
            password: '${PASS}'
            migrations: true
