const env = {
  DEBUG: process.env.DEBUG!,
  PORT: process.env.PORT!,
  DATABASE: process.env.DATABASE!,
  MX_API_KEY: process.env.MX_API_KEY!,
  MX_CLIENT_ID: process.env.MX_CLIENT_ID!,
  MAILGUN_DOMAIN: process.env.MAILGUN_DOMAIN!,
  MAILGUN_API_KEY: process.env.MAILGUN_API_KEY!,
  USER_COLORS: process.env.USER_COLORS,
  SENTRY_DSN: process.env.SENTRY_DSN,
  MAIL_FROM: process.env.MAIL_FROM!,
  MAIL_LINK_BASE: process.env.MAIL_LINK_BASE!,
  MAIL_USER_CREATION_CONFIRMATION_LINK: process.env
    .MAIL_USER_CREATION_CONFIRMATION_LINK!,
  MAIL_ACCOUNT_CREATION_NOTIFICATION_LINK: process.env
    .MAIL_ACCOUNT_CREATION_NOTIFICATION_LINK!,
  MAIL_STORY_PUBLICATION_NOTIFICATION_LINK: process.env
    .MAIL_STORY_PUBLICATION_NOTIFICATION_LINK!,
}

export default env
